// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TsWwPayments.Databases;

#nullable disable

namespace TsWwPayments.Migrations
{
    [DbContext(typeof(PaymentsContext))]
    partial class PaymentsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TsWwPaymentsModelApi.Models.PaymentsAccount", b =>
                {
                    b.Property<int>("PaymentsAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentsAccountId"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.HasKey("PaymentsAccountId");

                    b.ToTable("PaymentsAccounts");
                });

            modelBuilder.Entity("TsWwPaymentsModelApi.Models.Transmission", b =>
                {
                    b.Property<int>("TransmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransmissionId"), 1L, 1);

                    b.Property<string>("ActionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DoneAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentsAccountId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TransferredAmount")
                        .HasColumnType("bigint");

                    b.HasKey("TransmissionId");

                    b.HasIndex("PaymentsAccountId");

                    b.ToTable("Transmissions");
                });

            modelBuilder.Entity("TsWwPaymentsModelApi.Models.Transmission", b =>
                {
                    b.HasOne("TsWwPaymentsModelApi.Models.PaymentsAccount", "PaymentsAccount")
                        .WithMany("Transmissions")
                        .HasForeignKey("PaymentsAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentsAccount");
                });

            modelBuilder.Entity("TsWwPaymentsModelApi.Models.PaymentsAccount", b =>
                {
                    b.Navigation("Transmissions");
                });
#pragma warning restore 612, 618
        }
    }
}
