name: Deploy to IIS

on:
    workflow_dispatch:

jobs:
  build-and-deploy:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Set Secrets
      run: |
        dotnet user-secrets set "BotConfigs:HostAddress" "${{ secrets.HOST_ADDR }}" --id "ed9fd539-c357-4572-ab55-2a0e59cccac1"
        dotnet user-secrets set "BotConfigs:BotToken" "${{ secrets.BOT_TOKEN }}" --id "ed9fd539-c357-4572-ab55-2a0e59cccac1"

    - name: Build with dotnet
      run: dotnet build --configuration Release .\TsWwPayments

    - name: dotnet publish 
      run: |
        dotnet publish -c Release -o paymentsapp .\TsWwPayments
    - name: Deploy to IIS
      run: |
        iisreset /stop
        Copy-Item ./paymentsapp/* C:\Users\Administrator\Desktop\Site\Payments -Recurse -Force
        iisreset /start
